# Generated by Django 4.1.7 on 2023-03-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipy_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipyIngredient',
        ),
    ]
