# Generated by Django 4.1.7 on 2023-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy_app', '0002_delete_recipyingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipy',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipies', to='recipy_app.ingredient'),
        ),
    ]
